import './portal.css';
import {api,refreshIcons,escapeHTML,fileSize,fileDate} from './shared.js';
import {ModelViewer} from './viewer.js';
const $=id=>document.getElementById(id);let projects=[],selected=null,file=null,measurements=[],request=0,projectRequest=0,viewer;
const toast=message=>{$('toast').textContent=message;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,6000);};
const message=(title,detail='')=>{$('viewer-message').hidden=false;$('viewer-message').innerHTML=`<h3>${escapeHTML(title)}</h3><p>${escapeHTML(detail)}</p>`;};
const units=()=>file?.units==='m'?'m':file?.units==='ft'?'ft':'units';
function clearMeasurements(){measurements=[];viewer?.clearMeasurements();$('measurements').replaceChildren();$('measurement-count').textContent='0';$('measurement-empty').hidden=false;}
try{viewer=new ModelViewer($('viewer'),distance=>{measurements.push(distance);$('measurements').innerHTML=measurements.map(n=>`<li>${n.toFixed(3)} ${units()}</li>`).join('');$('measurement-count').textContent=measurements.length;$('measurement-empty').hidden=true;});}catch(error){message('3D viewer unavailable','This browser could not initialize WebGL. Model downloads remain available.');}
function renderProjects(){const query=$('project-search').value.toLowerCase();$('project-list').innerHTML=projects.filter(p=>p.name.toLowerCase().includes(query)).map(p=>`<button class="project-item" data-project="${p.id}" aria-current="${p.id===selected?.id}"><strong>${escapeHTML(p.name)}</strong><small>${p.file_count} deliver${p.file_count===1?'y':'ies'}${p.sample?' / Demo':''}</small></button>`).join('')||'<p class="sidebar-message">No projects found.</p>';document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>selectProject(b.dataset.project));}
async function refreshProjects(){({projects}=await api('/projects'));renderProjects();}
function display(){viewer?.display($('show-grid').checked,$('show-wireframe').checked,Number($('point-size').value));$('point-size-value').value=$('point-size').value;}
function clip(){const axis=$('clip-axis').value;$('clip-position').disabled=axis==='none';$('clip-value').value=$('clip-position').value+'%';viewer?.clip(axis,Number($('clip-position').value));}
async function loadFile(id){const ticket=++request;file=selected.files.find(f=>f.id===id);clearMeasurements();viewer?.clear();
  for(const id of ['info-format','info-vertices','info-triangles','info-date','dimension-x','dimension-y','dimension-z'])$(id).textContent='--';
  $('viewer-state').textContent='No model loaded';$('model-size').textContent='';$('unit-note').textContent='Model units';$('measurement-label').hidden=true;$('measure-toggle').setAttribute('aria-pressed','false');if(viewer)viewer.measuring=false;
  $('viewer-mode').textContent='PERSPECTIVE';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view==='perspective')));
  $('download-model').removeAttribute('href');$('download-model').setAttribute('aria-disabled','true');document.querySelectorAll('.viewer-toolbar button:not(#fullscreen)').forEach(b=>b.disabled=true);if(!file){message('No deliveries yet','Your project files will appear here when ready.');return;}
  $('download-model').href=`/api/files/${file.id}/content?download=1`;$('download-model').setAttribute('aria-disabled','false');$('model-size').textContent=fileSize(file.size);$('mobile-file').textContent=file.name;$('info-format').textContent=file.name.split('.').pop().toUpperCase();$('info-date').textContent=fileDate(file.created);$('unit-note').textContent=file.units==='units'?'Unspecified source units':'Source units: '+units();message('Loading model',file.name);if(!viewer){message('3D viewer unavailable','Download the model to inspect it locally.');return;}
  try{const response=await fetch(`/api/files/${file.id}/content`);if(!response.ok)throw new Error('The model could not be retrieved.');const buffer=await response.arrayBuffer();if(ticket!==request)return;const info=await viewer.load(buffer,file.name);if(ticket!==request){viewer.clear();return;}$('viewer-message').hidden=true;$('viewer-state').textContent='MODEL READY';$('info-vertices').textContent=info.vertices.toLocaleString();$('info-triangles').textContent=info.triangles.toLocaleString();for(const axis of ['x','y','z'])$('dimension-'+axis).textContent=info.size[axis].toFixed(2)+' '+units();document.querySelectorAll('.viewer-toolbar button').forEach(b=>b.disabled=false);display();clip();}catch(error){if(ticket===request)message('Preview unavailable',error.message+' You can still download the original file.');}
}
async function selectProject(id){const ticket=++projectRequest;try{const data=await api('/projects/'+id);if(ticket!==projectRequest)return;selected={...data.project,files:data.files};$('project-name').textContent=selected.name;$('header-project').textContent=selected.name;$('project-description').textContent=selected.description;$('sample-badge').hidden=!selected.sample;$('project-status').textContent='PROJECT';$('model-select').innerHTML=selected.files.map(f=>`<option value="${f.id}">${escapeHTML(f.name)}</option>`).join('')||'<option>No deliveries yet</option>';$('model-select').disabled=!selected.files.length;renderProjects();closeDrawers();await loadFile(selected.files[0]?.id);}catch(error){toast(error.message);}}
function closeDrawers(){for(const [button,panel] of [['toggle-projects','project-sidebar'],['toggle-inspector','inspector']]){$(button).setAttribute('aria-expanded','false');$(panel).classList.remove('is-open');}}
for(const [button,panel] of [['toggle-projects','project-sidebar'],['toggle-inspector','inspector']])$(button).onclick=()=>{const open=!$(panel).classList.contains('is-open');closeDrawers();$(panel).classList.toggle('is-open',open);$(button).setAttribute('aria-expanded',String(open));};
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawers();});
$('project-search').oninput=renderProjects;$('model-select').onchange=e=>loadFile(e.target.value);
$('fit-view').onclick=()=>viewer.fit();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{viewer.fit(b.dataset.view);$('viewer-mode').textContent=b.dataset.view.toUpperCase();document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});
$('measure-toggle').onclick=()=>{viewer.measuring=!viewer.measuring;$('measure-toggle').setAttribute('aria-pressed',String(viewer.measuring));$('measurement-label').hidden=!viewer.measuring;$('measurement-label').textContent='Select two points on the model';};$('clear-measurements').onclick=clearMeasurements;
for(const id of ['show-grid','show-wireframe','point-size'])$(id).oninput=display;for(const id of ['clip-axis','clip-position'])$(id).oninput=clip;
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('viewer-shell').requestFullscreen();}catch{toast('Full screen is unavailable in this browser.');}};
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('account-settings').onclick=()=>$('password-dialog').showModal();$('new-client').onclick=()=>{$('client-result').hidden=true;$('client-form').reset();$('client-dialog').showModal();};
$('new-project').onclick=async()=>{try{const {clients}=await api('/clients');$('project-client').innerHTML=clients.map(c=>`<option value="${c.id}">${escapeHTML(c.name)} (${escapeHTML(c.email)})</option>`).join('');$('project-dialog').showModal();}catch(e){toast(e.message);}};
$('upload-model').onclick=()=>{if(!selected)return toast('Create or select a project first.');$('upload-dialog').showModal();};
function form(id,action){$(id).onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]'),status=e.target.querySelector('.form-message');button.disabled=true;status.textContent='';try{await action(new FormData(e.target));}catch(error){status.textContent=error.message;}finally{button.disabled=false;}};}
form('project-form',async data=>{const result=await api('/projects',{method:'POST',body:JSON.stringify(Object.fromEntries(data))});$('project-dialog').close();$('project-form').reset();await refreshProjects();await selectProject(result.project.id);});
form('upload-form',async data=>{if(data.get('model').size>100*1024*1024)throw new Error('The upload limit is 100 MB.');await api(`/projects/${selected.id}/files`,{method:'POST',body:data});$('upload-dialog').close();$('upload-form').reset();await refreshProjects();await selectProject(selected.id);toast('Delivery uploaded.');});
form('client-form',async data=>{const result=await api('/clients',{method:'POST',body:JSON.stringify(Object.fromEntries(data))});$('client-result').hidden=false;$('temporary-password').value=result.temporaryPassword;});
form('password-form',async data=>{await api('/password',{method:'POST',body:JSON.stringify(Object.fromEntries(data))});location.href='./login.html?updated=1';});
$('sign-out').onclick=async()=>{try{await api('/logout',{method:'POST'});location.href='./login.html';}catch(e){toast(e.message);}};
refreshIcons();
async function initialize(){try{const {user}=await api('/session');$('account-name').textContent=user.name;if(user.role==='admin')document.querySelectorAll('.admin-only').forEach(n=>n.hidden=false);await refreshProjects();if(projects.length)await selectProject(projects[0].id);else message('No projects yet','Your assigned deliveries will appear here.');}catch(error){toast(error.message);}}
initialize();
